version: '3.8'
services:
  api:
    image: api
    container_name: api
    restart: unless-stopped
    networks:
      - app-network
    command: npm run start:prod
    build:
      target: prod
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app/api
      - /home/node/app/api/node_modules
      - web-root:/home/node/app/client/dist
    environment:
      NODE_ENV: production
      DB_HOST: host.docker.internal
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email alex@alexpepper.us --agree-tos --no-eff-email --force-renewal -d alexpepper.net  -d www.alexpepper.net
volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge
