version: '3.8'
services:
  api:
    image: api
    container_name: api
    restart: unless-stopped
    command: npm run start:prod
    build:
      target: prod
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/api
      - /usr/src/app/api/node_modules
    networks:
      - app-network
    environment:
      NODE_ENV: production
      DB_HOST: host.docker.internal
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/home/node/app/client/dist
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/home/node/app/client/dist
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/home/node/app/client/dist --email alex@alexpepper.us --agree-tos --no-eff-email --staging -d alexpepper.net  -d www.alexpepper.net
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/node/app/client/dist/
      o: bind

networks:
  app-network:
    driver: bridge
